### ISSUE TITLE
Some listings showing up in both Live and Secondary tabs at the same time

### ISSUE THREAD

**Issue by sjc5** [holaplex/metaplex#188]
Example: [this auction](https://friedghost.holaplex.com/listings/72ehf4f3JJYNve8Ng9cPsy3pCkxLLEDLChAYH7AEuS78) is showing up both in the Live and Secondary Listings tabs when you visit https://friedghost.holaplex.com.

Live view:

![Screen Shot 2021-12-29 at 11 03 10 AM](https://user-images.githubusercontent.com/58375830/147686402-4d0b58d4-5225-41f1-b26e-7a7837a406f7.png)

Secondary view: 

![Screen Shot 2021-12-29 at 11 03 19 AM](https://user-images.githubusercontent.com/58375830/147686406-54a60dff-28c6-4ec7-9b2a-38c4b08d651f.png)

**Comment by kespinola** [comment]
I checked out the admin area for the storefront. There is 1 auction cache missing. Getting that record will get the app to de-dup it but what we should adjust is not showing anything as secondary when no cache is present.

**Comment by sjc5** [comment]
> I checked out the admin area for the storefront. There is 1 auction cache missing. Getting that record will get the app to de-dup it but what we should adjust is not showing anything as secondary when no cache is present.

Thanks Kyle, are you already digging in?  If not I can take a crack at it.

**Comment by sjc5** [comment]
Fixed by #189
