### ISSUE TITLE
Indicator for limited edition sales

### ISSUE THREAD

**Issue by b2kdaman** [holaplex/metaplex#191]
There's no way to see how many items were sold
![Group 3](https://user-images.githubusercontent.com/7579297/147790934-c24e9370-cb08-4adc-93ef-82b832446d99.png)

**Comment by dandlezzz** [comment]
addressed in https://github.com/holaplex/metaplex/pull/193

**Comment by sjc5** [comment]
Resolved again in #228. Closing
