### ISSUE TITLE
Hide defective auctions from ended tab

### ISSUE THREAD

**Issue by kespinola** [holaplex/metaplex#221]
## Issue
Currently, listings that fail to complete may appear on the ended tab in a state of ended and no nft associated to the listing.

## Goal
Defective auctions are filtered out of the list of viewable listings on the ended tab.

## Examples

https://johnlestudio.holaplex.com/listings?view=ended

<img width="1335" alt="Screen Shot 2022-01-08 at 5 11 39 PM" src="https://user-images.githubusercontent.com/2388118/148665307-0aaa29c7-1ff3-463f-88c2-e271e5dd79f3.png">

**Comment by sjc5** [comment]
closing.  resolved by #244
