### ISSUE TITLE
Redesign Bidding for Listings using Tick size

### ISSUE THREAD

**Issue by kristianeboe** [holaplex/metaplex#264]
When bidding on live auctions where: e.g. the starting price is set to 0.1 but tick size is set to 0.5, an error occurs because the minimum bid here is actually 0.5. (issue linked)

# Solution
Add validation in the auction listing process for starting price and tick size fields:

Starting bid must be an multiple of the tick size.

**Comment by kristianeboe** [comment]
Related: 
- When you connect a wallet to place a bid, the 'submit' button starts off in a load state
-  - Only allow 'submit' button to enter load state once clicked

- To avoid error caused by starting price being less than or equal to tick size, add validation to listing process input fields - starting price must be greater than tick size. (issue linked) 

## Design tbc 
- Example of issue (starting price .01, tick size .5, minimum bid shown in placeholder text and error message is incorrect)
![image](https://user-images.githubusercontent.com/10433154/150839475-f67a05cb-664a-4a2d-95a6-1831c2f50044.png)

- Change placeholder text to "◎ e.g. (minimum bid)"

- Only show error message when there is an invalid amount currently entered into the field. If the invalid entry gets deleted, remove the error message.

- When an invalid amount is entered into the field, change the error message to: "Please enter a minimum bid of (minimum bid)"

- Only show 1 error message at a time. If the connected wallet has a balance less than or equal to the minimum bid, and an invalid amount is currently entered into the field, only show the wallet balance error.
- - Change wallet balance error message to: "Insufficient funds in your wallet."

![image](https://user-images.githubusercontent.com/10433154/150839566-d460ae0b-a7fc-4455-8b5e-db5708cd791c.png)

**Comment by sjc5** [comment]
hi @kristianeboe, the first part of this was resolved by #231.  should we close and break out the remaining items into a new issue?

**Comment by sjc5** [comment]
@kristianeboe closed this as the items in comment 1 are resolved.  will move your second comment over to a new issue
