### ISSUE TITLE
TPS warning banner

### ISSUE THREAD

**Issue by kristianeboe** [holaplex/metaplex#281]
If the Solana Network has less than 1500 TPS (transactions pr second) it's hard for us to guarantee that actions like bidding, listing and minting will work correctly. 

If a user is about to do one of these actions we should make some API calls and figure out how the network is doing, and if less than 1500 TPS show a warning banner.

**Comment by b2kdaman** [comment]
I think its better to have Network item in top navbar with circle that indicates how network performs now

**Comment by davetorbeck** [comment]
I'm in agreement, I think this would be better placed somewhere globally rather than injecting it into the page-specific content.  Something like a toast/notification or in the top navbar as @b2kdaman suggested.  It would be easier implementation wise as well.

CC: @damianr @bellebellesol @kristianeboe

**Comment by damianr** [comment]
I liked the idea of only mentioning the network issues if it was at a relevant point for the user. If they are just browsing we don't need to advertise that the network has issues. It's not a big deal but wanted to mention it.

**Comment by bellebellesol** [comment]
I agree with Damian and Kristian. Ideally we don't show any TPS messaging on holaplex.com as it's not necessary there. 

If we can do the TPS check in the background, then we can surface the warning banner in the key places when it's relevant to the user.

**Comment by sjc5** [comment]
Closing based on recent reduction / elimination of the need for a TPS banner.
