### ISSUE TITLE
Metaplex ended listings filter + (participation badge -> no)

### ISSUE THREAD

**Issue by kristianeboe** [holaplex/metaplex#333]
1. Add a filter for Ended auctions where no bids where accepted
2. Detect if a user participated in a listing and add a badge

**Comment by kristianeboe** [comment]
Probably something like this, just need the toggle. 
![image](https://user-images.githubusercontent.com/10433154/155496009-9e21e275-700b-4928-b373-2829da7ec4f5.png)

**Comment by bellebellesol** [comment]
Design: https://www.figma.com/file/MxzeTx3eaLDISbxRBuI9JU/Miscellaneous?node-id=95%3A3422

**Comment by kristianeboe** [comment]
No participation badge in the end.
